

export const GET_APPOINTMENTS = "GET_APPOINTMENTS"


export const GET_SLIDERIMAGE = "GET_SLIDERIMAGE"
export const DELETE_SLIDERIMAGE = "DELETE_SLIDERIMAGE"
export const ADD_SLIDERIMAGE = "ADD_SLIDERIMAGE"


export const GET_ABOUTINFO = "GET_ABOUTINFO"
export const ADD_ABOUTINFO = "ADD_ABOUTINFO"
export const UPDATE_ABOUTINFO = "UPDATE_ABOUTINFO"
export const DELETE_ABOUTINFO = "DELETE_ABOUTINFO"


export const ADD_DOCTOR = "ADD_DOCTOR"
export const GET_DOCTORLIST = "GET_DOCTORLIST"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"