
export const SET_LOADER = "SET_LOADER"

export const GET_APPOINTMENTS = "GET_APPOINTMENTS"
export const DELETE_APPOINTMENTS = "DELETE_APPOINTMENTS"



export const GET_SLIDERIMAGE = "GET_SLIDERIMAGE"
export const DELETE_SLIDERIMAGE = "DELETE_SLIDERIMAGE"
export const ADD_SLIDERIMAGE = "ADD_SLIDERIMAGE"


export const GET_ABOUTINFO = "GET_ABOUTINFO"
export const ADD_ABOUTINFO = "ADD_ABOUTINFO"
export const UPDATE_ABOUTINFO = "UPDATE_ABOUTINFO"
export const DELETE_ABOUTINFO = "DELETE_ABOUTINFO"


export const ADD_DOCTOR = "ADD_DOCTOR"
export const GET_DOCTORLIST = "GET_DOCTORLIST"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"


export const GET_SERVICES = "GET_SERVICES"
export const ADD_SERVICES = "ADD_SERVICES"
export const UPDATE_SERVICES = "UPDATE_SERVICES"
export const DELETE_SERVICES = "DELETE_SERVICES"

export const ADD_GAL_IMAGE = "ADD_GAL_IMAGE"
export const GET_GAL_IMAGE = "GET_GAL_IMAGE"
export const DELETE_GAL_IMAGE = "DELETE_GAL_IMAGE"


export const GET_BLOG = "GET_BLOG"
export const ADD_BLOG = "ADD_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const UPDATE_BLOG = "UPDATE_BLOG"

export const GET_CLINIC_DATA = "GET_CLINIC_DATA"
export const UPDATE_CLINIC_DATA = "UPDATE_CLINIC_DATA"











