

export const GET_APPOINTMENTS = "GET_APPOINTMENTS"


export const GET_SLIDERIMAGE = "GET_SLIDERIMAGE"
export const DELETE_SLIDERIMAGE = "DELETE_SLIDERIMAGE"
export const ADD_SLIDERIMAGE = "ADD_SLIDERIMAGE"


export const GET_ABOUTINFO = "GET_ABOUTINFO"
export const ADD_ABOUTINFO = "ADD_ABOUTINFO"